// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col items-center\"><h1 class=\"text-xl p-4\">ayoradio</h1><div class=\"text-center\"><span class=\"text-primary-400\">small web utility, utilizing arp-scan, go's os/exec, gocron, and chi (routing) <br></span> <span class=\"text-primary-500\">detects local devices presence (mobile-phone) and plays bgm beats to relax/study to <br></span> <span class=\"text-primary-400\">also features custom-playback, playlist, and default controls (obv) <br></span> <span class=\"text-primary-500\">design by me (naufal.suryasumirat), flawless ui design amirite? <br></span> <span class=\"text-primary-400\">built with golang, templ, tailwind css, htmx (GOTTH stack) <br></span> <span class=\"text-primary-500\">running on debian bookworm 12.9 (rpi 5) <br></span></div><div class=\"flex flex-col items-center mt-6\"><span class=\"text-white text-center pb-2\">mandatory fastfetch output: <br></span> <img class=\"rounded\" src=\"/static/images/fastfetch-rpi.png\" width=\"300\" height=\"300\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
